cmd_/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/subcmd-config.o := gcc -Wp,-MD,/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/.subcmd-config.o.d -Wp,-MT,/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/subcmd-config.o -ggdb3 -Wall -Wextra -std=gnu99 -fPIC -O3 -Werror -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -I/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/include/ -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wno-type-limits -Wstrict-aliasing=3 -Wshadow -Werror -Wbad-function-cast -Wdeclaration-after-statement -Wformat-security -Wformat-y2k -Winit-self -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wno-system-headers -Wold-style-definition -Wpacked -Wredundant-decls -Wstrict-prototypes -Wswitch-default -Wswitch-enum -Wundef -Wwrite-strings -Wformat -Wno-type-limits -Wstrict-aliasing=3 -Wshadow -Wno-switch-default -Wno-switch-enum -Wno-packed -Wno-nested-externs -Wall -Wmissing-prototypes -Wstrict-prototypes -O2 -fomit-frame-pointer -std=gnu11 -I ./scripts/include -g -I/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/include -I/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/arch/x86/include/uapi -I/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/arch/x86/include -I/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/include -I/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/arch/x86/include -I/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/include -D"BUILD_STR(s)=$(pound)s" -c -o /disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/subcmd-config.o subcmd-config.c

source_/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/subcmd-config.o := subcmd-config.c

deps_/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/subcmd-config.o := \
  /usr/include/stdc-predef.h \
  subcmd-config.h \

/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/subcmd-config.o: $(deps_/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/subcmd-config.o)

$(deps_/disk/scratch/operating_systems/s2567658/CW1/Task1/linux-6.12.67/tools/objtool/libsubcmd/subcmd-config.o):
